// Do not edit. This file is machine generated by the Resource DLL Wizard.

library LevEdit;

{ITE} {DFMFileType} {ComHilfe.dfm}
{ITE} {DFMFileType} {ComInfo.dfm}
{ITE} {DFMFileType} {LevMain.dfm}
{ITE} {DFMFileType} {LevOptions.dfm}
{ITE} {DFMFileType} {LevSpeicherung.dfm}
{ITE} {DFMFileType} {LevSplash.dfm}
{ITE} {RCFileType} {LevEdit_DRC.rc}

{$R 'ComHilfe.dfm' 'HilfeForm:TForm'}
{$R 'ComInfo.dfm' 'InfoForm:TForm'}
{$R 'LevMain.dfm' 'MainForm:TForm(DXForm)'}
{$R 'LevOptions.dfm' 'LevelForm:TForm'}
{$R 'LevSpeicherung.dfm' 'SpeicherungForm:TForm'}
{$R 'LevSplash.dfm' 'SplashForm:TForm'}
{$R 'LevEdit_DRC.res' 'LevEdit_DRC.rc'}

{$E ENU}

begin
end.
