// Do not edit. This file is machine generated by the Resource DLL Wizard.

library SpaceMission;

{ITE} {DFMFileType} {ComHilfe.dfm}
{ITE} {DFMFileType} {ComInfo.dfm}
{ITE} {DFMFileType} {GamCheat.dfm}
{ITE} {DFMFileType} {GamMain.dfm}
{ITE} {DFMFileType} {GamSpeicherung.dfm}
{ITE} {DFMFileType} {GamSplash.dfm}
{ITE} {RCFileType} {SpaceMission_DRC.rc}

{$R 'ComHilfe.dfm' 'HilfeForm:TForm'}
{$R 'ComInfo.dfm' 'InfoForm:TForm'}
{$R 'GamCheat.dfm' 'CheatForm:TForm'}
{$R 'GamMain.dfm' 'MainForm:TForm(DXForm)'}
{$R 'GamSpeicherung.dfm' 'SpeicherungForm:TForm'}
{$R 'GamSplash.dfm' 'SplashForm:TForm'}
{$R 'SpaceMission_DRC.res' 'SpaceMission_DRC.rc'}

{$E ENU}

begin
end.
